services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:fU7L0T6UDxpSfnc0jNuIE8QWTqMfq2L7F6xI9XSgNzMOwYHPhRG9Fj4zJeL0i90k@185.241.210.48:7800/postgres
      JWT_SECRET: change-me-in-production
      EMAIL_HOST: ""
      EMAIL_PORT: "587"
      EMAIL_USER: ""
      EMAIL_PASS: ""
      CRON_SECRET: change-me-in-production
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
